---
# tasks file for webserver

- name: opdater alle pakker
  yum: 
    name: '*' 
    state: latest
    update_cache: yes

- name: Installer seneste udgave af Apache
  yum:
    name: httpd
    state: latest


- name: Enable Service (Httpd, Firewalld)
  ansible.builtin.systemd:
    name: "{{ item }}"
  with_items:
    - httpd
    - firewalld
  notify:
     - Make sure httpd unit is running
     - Make sure firewalld unit is running


- name: kør bash command til kopiering af config filer
  ansible.builtin.command: cp /etc/httpd/conf/httpd.conf /backup/
  become: yes
  notify:
     - Make sure httpd unit is restarted

- name: insert hjemmeside index.html fil
  ansible.builtin.template:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0754'
  notify: 
      - Make sure httpd unit is restarted

- name: insert hjemmeside config fil.
  ansible.builtin.template:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    group: wheel
    mode: 644
  become: yes
  notify: 
      - Make sure httpd unit is restarted

- name: Åben firewalld adgang til tcp port 80 (http)
  firewalld:
   port: 80/tcp
   zone: public
   state: enabled
   permanent: yes
  notify:
    - Make sure firewalld service is restarted

- name: Åben firewalld adgang til tcp port 22 (ssh)
  firewalld:
   port: 22/tcp
   zone: public
   state: enabled
   permanent: yes
  notify:
    - Make sure firewalld service is restarted