---

# tasks file for backup-files
- name: byg backup mappe til conf filer
  ansible.builtin.file:
    path: /backup
    state: directory
    owner: root 
    group: root
    mode: '0766'
  become: yes
  
- name: Run bash command to copy config files
  ansible.builtin.command: cp "{{ item }}" /backup
  with_items:
      - /etc/ssh/sshd_config
      - /etc/selinux/semanage.conf
      - /etc/sysconfig/network-scripts/ifcfg-eno1
  become: yes
