---
# defaults file for webserver
# Network interface name, Relevant for firewalld configuration
Interface: eth0
#Httpd Conf
ServerRoot: "/etc/httpd"
ListenPort: 80
#Website
Title: Gruppe 4
BodyHeadder: Oops!... I Did It Again
Paragraph: Mmm, yeah Yeah, yeah, yeah, yeah, yeah,<br> yeah Yeah, yeah, yeah, yeah, yeah, yeah <br> I think I did it again <br> I made you believe we're more than just friends <br> Oh, baby, it might seem like a crush <br> But it doesn't mean that I'm serious <br> 'Cause to lose all my senses <br> That is just so typically me <br> Ooh, baby, baby Oops, I did it again <br> I played with your heart <br> Got lost in the game <br> Oh, baby, baby Oops, you think I'm in love <br> That I'm sent from above I'm not that innocent