---
# handlers file for webserver
- name: Make sure httpd unit is running
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: yes

- name: Make sure firewalld unit is running
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes


