---
# handlers file for webserver
- name: Make sure httpd unit is running
  ansible.builtin.systemd:
    name: httpd
    state: started


- name: Make sure firewalld unit is running
  ansible.builtin.systemd:
    name: firewalld
    state: started


- name: Make sure httpd unit is restarted
  ansible.builtin.systemd:
    name: httpd
    state: started


- name: Make sure firewalld service is restarted
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
    
