---
# tasks file for webserver

- name: update alle pakker
  yum: 
    name: '*' 
    state: latest
    update_cache: yes

- name: Installer services & værktøjer
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - httpd
    - epel-release
    - vim
    - bind-utils

- name: Enable Services (Httpd, Firewalld)
  ansible.builtin.systemd:
    enabled: yes
    name: "{{ item }}"
  with_items:
    - httpd
    - firewalld

- name: inserting website index.html file
  ansible.builtin.template:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: wheel
    mode: 750
  become: yes
  notify: 
      - Make sure httpd unit is running


- name: inserting webserver config file.
  ansible.builtin.template:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    group: wheel
    mode: 644
  become: yes
  notify: 
      - Make sure httpd unit is running


- name: firewalld rules on relevant ports.
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - http
    - ssh
  notify:
      - Make sure firewalld unit is running