---
# tasks file for webserver

- name: upgrade all packages
  yum: 
    name: * 
    state: latest

- name: Installer resurcer
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - httpd
    - epel-release
    - vim
    - bind-utils

